file_names = {'basic_plot_sineedge',...
    'random_matrix_eigenvalue',...
    'plot_matrix_data1',...
    'plot_matrix_data2',...
    'sine_wave_hold_all',...
    'color_order',...
    'set_axis_lineseries',...
    'log_scale',...
    'plot_multiple_bessel',...
    'set_multiple_line_styles',...
    'set_multiple_line_multiple_style',...
    'cell_array_set_multiple_properties',...
    'set_axis_lineseries_text',...
    'lcg_histogram',...
    'fine_tune_histogram',...
    'bar_chart',...
    'area_plot',...
    'pie_chart',...
    'stem_sine',...
    'subplot_sine',...
    'polar_butterfly_curve',...
    'scatter_linear_fitting',...
    'contour_peaks',...
    'plot3D_brownian_motion',...
    'lorenz_attractor',...
    'mesh_3D_sinc',...
    'surf_3D_sinc',...
    'quiver_gradient'};
%     'animation_plot3D_brownian_motion',...
%     'attanimation_lorenz_attractor',...
%     'animation_wave_equation',...
for file_name = file_names
    export_figure(file_name{:})
end