run figure_style
x = (0:0.1:15);   % Range of x.
alpha = [0:3,10]; % Alpha = {0 1 2 3 10}.
J = zeros(length(alpha),length(x)); % J_alpha(x).
for I=1:length(alpha),
    J(I,:) = besselj(alpha(I), x);
end
color_order = jet(length(alpha)); % Use jet colormap.
set(gca,'colororder',color_order,... % Set color order
        'fontsize',font_size);              % and font size.
hold all;   % Keep the color order.
plot(x,J,'LineWidth',line_width);  % Plot matrix data.
%% Fine Tune the plot.
% X and Y labels using LaTeX.
xlabel('$x$','Position',[6.5 -0.6 1.0],...
    'Interpreter','LaTeX','FontSize',text_size);
ylabel('$J_{\alpha}(x)$','Rotation',0,...
    'Position',[-1.5 0.4 1.0],...
    'Interpreter','LaTeX','FontSize',text_size);
% Change X and Y tick positions and labels.
set(gca,'XTick',(0:15),...
'XTickLabel',[{'0'}; {'1'};{'2'};...
{'3'};{' '};{' '};{' '};{' '};...
{' '};{' '};{'10'};{' '};{' '};...
{' '};{' '};{'15'}],...
'YTick',(-.4:.2:1),...
'YTickLabel',[{' '},{' '},{'0.0'},...
{' '},{' '},{' '},{' '},{'1.0'}],...
'XLim',[0 15],'YLim',[-0.5 1.1]);   % Set x and y limit.
% Put text annotations.
for I = 1:length(alpha),
    [mx,ind] = max(J(I,:)); % Find the location of the maximum.
    text(x(ind)+0.2,mx+0.05,... % Put text near the maximum.
        ['$\alpha = ',num2str(alpha(I)),'$'],...
        'Interpreter','LaTeX','FontSize',text_size);
end
% export_fig('../fig/graded_task_01','-pdf','-transparent')